---
title: "Lecture 1. Introduction"
date: 2026-03-09
format:
    html:
        toc: true
        toc-depth: 2
        number-sections: false
        include-in-header:
            text: |
                <meta name="robots" content="noindex, nofollow">
    typst: default 
---

::: {.hidden}
\newcommand{\sp}{\operatorname{sp}}

\newcommand{\Hom}{\operatorname{Hom}}
\newcommand{\GL}{\operatorname{GL}}
\newcommand{\Gal}{\operatorname{Gal}}
\newcommand{\Spec}{\operatorname{Spec}}

\newcommand{\Rep}{\mathrm{Rep}}
\newcommand{\Vect}{\mathrm{Vect}}

\newcommand{\bC}{\mathbf{C}}
\newcommand{\bF}{\mathbf{F}}
\newcommand{\bG}{\mathbf{G}}
\newcommand{\bQ}{\mathbf{Q}}
\newcommand{\bZ}{\mathbf{Z}}

\newcommand{\et}{\mathrm{ét}}
\newcommand{\Betti}{\mathrm{Betti}}
\newcommand{\HT}{\mathrm{HT}}
\newcommand{\dR}{\mathrm{dR}}
\newcommand{\cris}{\mathrm{cris}}
\newcommand{\unr}{\mathrm{unr}}
\newcommand{\Fet}{\mathrm{Fét}}
:::

## Notations 

- $\overline{k}$: separable closure of a field $k$. 
- $\Gal_{k}$: absolute Galois group of a field $k$. 

## 1. Arithmetic perspective 

In number theory, one of the main character is \textit{$\ell$-adic Galois representations}. 

**Definition[^1].** Let $\Gamma$ be a profinite group. An \textit{$\ell$-adic representation} is a continuous group homomorphism 
$$ \rho: \Gamma \to \GL_{n}(\bQ_{\ell}). $$ 

**Examples.** 

1. For an abelian variety $A$ over a field $k$, the rational Tate module $V_{\ell}(A) \coloneqq \bQ_{\ell} \otimes_{\bZ_{\ell}} T_{\ell}(A)$ is an $\ell$-adic representation of $\Gal_{k}$. Here, the (integral) Tate module $T_{\ell}(A)$ is a $\bZ_{\ell}[\Gal_{k}]$-module 
$$ T_{\ell}(A) \coloneqq \varprojlim_{n} A[\ell^{n}](\overline{k}). $$

2. For a proper scheme $X$ over a field $k$, the étale cohomology $H_{\et}^{n}(X_{\overline{k}}, \bQ_{\ell})$ is an $\ell$-adic representation of $\Gal_{k}$. 

**Remark.** In fact, for an abelian variety $A$ over a field $k$, we obtain 
$$ T_{\ell}(A) = H_{\et}^1(A_{\overline{k}}, \bZ_{\ell})^{\vee} $$
as $\bZ_{\ell}[\Gal_{k}]$-modules. 

From now on, we focus on local Galois representations. Note that for a global Galois representation $\rho: \Gal_{\bQ} \to \GL(V)$, we can induce a local Galois representation $\rho_{p}: \Gal_{\bQ_{p}} \to \GL(V)$ by composing the restriction map $\Gal_{\bQ_{p}} \to \Gal_{\bQ}$.[^2] 

In number theory, local objects are simpler than global objects. In the local situation taking modulo reduction makes further simplification. Let us see how this happens for Tate modules of elliptic curve. 

Let $E$ be an elliptic curve over a local field $K$, say $\bQ_{p}$. Assume that $E$ has a good reduction, i.e., there is an elliptic curve $E_{\bZ_{p}}$ over $\Spec(\bZ_{p})$ whose generic fiber is isomorphic to $E$. Let $E_{\bF_{p}}$ be its special fiber. We want to compare two Tate modules $T_{\ell}(E)$ and $T_{\ell}(E_{\bF_{p}}$. To do so, we need a specialization map. 

$$ \sp: T_{\ell}(E) \to T_{\ell}(E_{\bF_{p}}). $$
In fact, we construct a map 
$$ \sp: G(\overline{\bQ_{p}}) \to G_{\bF_{p}}(\overline{\bF_{p}}) $$
for each $G = E_{\bZ_{p}}[\ell^{n}]$. Since $G_{\bZ_{p}}$ is proper, by the valuative criterion of properness, we obtain 
$$ G(\overline{\bQ_{p}}) = G_{\bZ_{p}}(\overline{\bZ_{p}}). $$
We compose this with the reduction map 
$$ G_{\bZ_{p}}(\overline{\bZ_{p}}) \to G_{\bF_{p}}(\overline{\bF_{p}}) $$
to obtain the specialization map. One can show that it is a homomorphism and Galois equivariant with respect to the reduction map $\Gal_{\bQ_{p}} \to \Gal_{\bF_{p}}$. 

If $\ell \perp p$, then $G = E_{\bZ_{p}}[\ell^{n}]$ is finite étale by the following fact. 

**Fact.** The kernel $E_{\bZ_{p}}[\ell^{n}]$ is a finite étale group scheme over $\Spec(\bZ_{p})$ for all $n$. 

In this case, the reduction map becomes a bijection by the following theorem. 

**Theorem ([Stacks Project, [Tag 09ZS](https://stacks.math.columbia.edu/tag/09ZS)]).** For a Henselian local ring $R$ with residue field $k$, the reduction defines equivalence of categories 
$$ \Fet(R) \to \Fet(k); \quad T \mapsto T_{k} $$

Indeed, we obtain 
$$ G_{\bZ_{p}}(\overline{\bZ_{p}}) = \varinjlim_{K'/K} \Hom_{\bZ_{p}}(\Spec(\sO_{K'}), G_{\bZ_{p}}) = \varinjlim_{K'/K} \Hom_{\bF_{p}}(\Spec(k_{K'}), G_{\bF_{p}}) = G_{\bF_{p}}(\overline{\bF_{p}}). $$

Therefore, we obtain a Galois equivariant isomorphism of $\bZ_{\ell}$-modules 
$$ \sp: T_{\ell}(E) \to T_{\ell}(E_{\bF_{p}}). $$
In particular, the Tate module $T_{\ell}(E)$ is unramified if it has a good reduction and $\ell \perp p$. In fact, the unramifiedness of Tate module is equivalent to the elliptic curve $E$ has a good reduction! 

**Theorem (Néron-Ogg-Shafarevich).** Let $A$ be an abelian variety over a local field $K$ with residual characteristic $p$. The following are equivalent. 

1. $E$ has a good reduction. 
2. For any $\ell \perp p$, the $\ell$-adic rational Tate module $V_{\ell}(E)$ is unramified. 
3. For some $\ell \perp p$, the $\ell$-adic rational Tate module $V_{\ell}(E)$ is unramified. 

The natural question is asking what can we say if $\ell = p$. For this case, the Tate module $T_{\ell}(E)$ and $T_{\ell}(E_{\bF_{p}})$ are *never* isomorphic! Indeed, while the rank of $T_{\ell}(E)$ is $2$, the rank of $T_{\ell}(E_{\bF_{p}})$ is at most $1$ as 
$$ E_{\bF_{p}}(p^{n}) \cong 0, \bZ/p^{n} \bZ. $$

Still, there is an answer to this question. 

**Theorem (Grothendieck).** An abelian variety $A$ over a local field $K$ has a good reduction if and only if $V_{p}(A)$ is *crystalline*. 

We will roughly explain about crystalline representations in the following sections. 

**Spoiler.** 

- As its name suggests, we will use crystalline cohomology in place of étale cohomology. 
- The p-adic counterpart of Tate module is *p-divisible group*. As there is a contravariant relationship between Tate modules and étale cohomology, there is a similar correspondence between p-divisible groups and crystalline cohomology. 

## 2. Geometric perspective 

In the previous section, we explained the arithmetic part of p-adic Hodge theory. Still, the question that why it is named with "p-adic Hodge" remains. This section would give an answer. 

### 2.1. Hodge-Tate comparison 

The classical Hodge decomposition is as follows. 

**Theorem (Hodge decomposition).** Let $X$ be a smooth proper scheme over $\bC$. There is a functorial[^3] isomorphism of $\bC$-vector spaces
$$ H_{\text{Betti}}^{n}(X, \bZ) \otimes_{\bZ} \bC \cong \bigoplus_{i+j = n} H^{i, j}(X). $$
Here, $H^{i, j}(X) = H^{i}(X, \Omega^{j}_{X/\bC})$ and there is the Hodge symmetry $\overline{H^{i,j}} = H^{j, i}$. In the other words, $H_{\text{Betti}}^n(X, \bZ)$ admits a natural $\bZ$-Hodge structure of weight $n$. 

Tate suggested and Faltings proved a $p$-adic version of this Hodge decomposition. Of course, the replacement of Betti cohomology is étale cohomology. To state this in the full generality, we introduce the notion, *p-adic fields*. 

**Definition.** A *$p$-adic field* is a characteristic $0$ complete discretely valued field with perfect residue field of characteristic $p$. 

**Remark.** Any $p$-adic field contains $\bQ_{p}$, the topological closure of $\bQ$. 

**Examples.** 

1. Finite extensions of $\bQ_{p}$ are $p$-adic fields. 
2. The completed maximal unramified field $\breve{K} \coloneqq \widehat{K^{\unr}}$ of a finite extension $K/\bQ_{p}$ is a $p$-adic field. 
3. For any $p$-adic field $K$ with residue field $k$, it contains the "maximal unramified subextension" $K_{0} \coloneqq W(k)[\frac{1}{p}]$. This field $K_{0}$ is a $p$-adic field. 
4. The completed algebraic closure $\bC_{K} \coloneqq \widehat{\overline{K}}$ of a $p$-adic field $K/\bQ_{p}$ is *not* a $p$-adic field. Its valuation gruop is $\bQ$. 

**Fact.** The completed algebraic closure $\bC_{K}$ of $K$ is algebraically closed. 

**Theorem (Faltings, Hodge-Tate decomposition).** Let $X$ be a smooth proper scheme over a $p$-adic field $K$. There is a functorial isomorphism 
$$ H_{\et}^n(X_{\overline{K}}, \bQ_{p}) \otimes_{\bQ_{p}} \bC_{K} \cong \bigoplus_{i+j = n} H^{i}(X, \Omega^{j}_{X/K}) \otimes_{K} \bC_{K}(-j). $$

Here, $\bC_{K}(-j)$ is the $(-j)$th *Tate twist* of $\bC_{K}$. Let us define it. 

**Definition.** The Tate module $\bZ_{p}(1)$ is defined as follows: 
$$ \bZ_{p}(1) \coloneqq T_{p}(\bG_{m}) \coloneqq \varprojlim_{n} \bG_{m}[p^{n}](\overline{K}) = \varprojlim_{n} \mu_{p^{n}}(\overline{K}). $$
The corresponding character $\chi: \Gal_{K} \to \bZ_{p}^\times$ is called the *$p$-adic cyclotomic character*. 

**Definition.** For a $p$-adic $\Gal_{K}$-module $M$, its $n$th Tate twist $M(n)$ is 
$$  
  M(n) \coloneqq 
  \begin{cases}
    M \otimes_{\bZ_{p}} \bZ_{p}(1)^{\otimes n} & n \ge 0 \\ 
    \Hom(\bZ_{p}(n), M) & n < 0.
  \end{cases}
$$

Also note that $\bC_{K}$ has a natural $\Gal_{K}$-action; an element $\sigma \in \Gal_{K}$ acts on $\bC_{K}$ by completing the continuous map $\sigma: \overline{K} \to \overline{K}$. 

The Hodge-Tate decomposition can be written in a fancy way using *Hodge-Tate period ring*. 

**Definition.** The *Hodge-Tate period ring* $B_{\HT}$ is a ($\bZ$-)graded $K$-algebra 
$$ B_{\HT} \coloneqq \bigoplus_{j \in \bZ} \bC_{K}(j). $$

**Theorem (Hodge-Tate decomposition, period ring version).** For any smooth proper $X$ over a $p$-adic field $K$, there is a grading respecting functorial isomorphism 
$$ H_{\et}^n(X_{\overline{K}}, \bQ_{p}) \otimes_{\bQ_{p}} B_{\HT} \cong \left( \bigoplus_{i+j = n} H^{i}(X, \Omega^{j}_{X/K}) \right) \otimes_{K} B_{\HT}. $$

**Remark.** 
- The grading on the left-hand side is comes from the grading of $B_{\HT}$. The grading on the right-hand side is the convolution grading.[^convolution grading]
- Taking $\operatorname{gr}^{0}$ to the period ring Hodge-Tate decomposition gives the previous Hodge-Tate decomposition. 

There is a very important theorem describing the Galois invariant part of $B_{\HT}$. 

**Theorem (Tate-Sen).** For an integer $j$, 
$$ 
  \bC_{K}(j)^{\Gal_{K}} =  
  \begin{cases}
    K & j = 0 \\ 
    0 & j \neq 0.
  \end{cases}
$$

This implies $B_{\HT}^{\Gal_{K}} = \bC_{K}$. Hence, if we take the Galois invariant to the Hodge-Tate decomposition, we obtain a grading respecting isomorphism 
$$ (H_{\et}^n(X_{\overline{K}}, \bQ_{p}) \otimes_{\bQ_{p}} B_{\HT})^{\Gal_{K}} \cong \bigoplus_{i+j = n} H^{i}(X, \Omega^{j}_{X/K}). $$
That means, *étale cohomology remembers Hodge cohomology*. 

### 2.2. de Rham comparison 

The Hodge-Tate decomposition is not so strong so we cannot obtain many useful properties from this. We need a stronger comparison theorem, and the next step is the *de Rham comparison*. Let us fist recall the classical theory. 

For a smooth proper scheme $X$ over $\bC$, the de Rham cohomology $H_{\dR}^n(X/\bC)$ admits a natural decreasing filtration, called a *Hodge filtration*: 
$$ H_{\dR}^n(X/\bC) = \mathrm{Fil}^{0}(H_{\dR}^n(X/\bC)) \supseteq \mathrm{Fil}^{1}(H_{\dR}^n(X/\bC)) \supseteq \cdots \supseteq \mathrm{Fil}^{n+1}(H_{\dR}^n(X/\bC)) = 0. $$
The de Rham comparison theorem is 
$$ H_{\text{Betti}}^n(X, \bZ) \otimes_{\bZ} \bC \cong H_{\dR}^n(X/\bC). $$
This recovers the Hodge decomposition via 
$$ H^{i, j} = \mathrm{Fil}^{j}(H_{\dR}^n(X/\bC)) \cap \overline{\mathrm{Fil}^{i}(H_{\dR}^n(X/\bC))}. $$
Although this is equivalent to the Hodge decomposition, in the $p$-adic case, it gives a stronger comparison. 

**Theorem (Faltings, de Rham comparison).** There is a filtered $K$-algebra $B_{\dR}$ such that, for a smooth proper scheme $X$ over a $p$-adic field $K$, there is a natural filtration respecting isomorphism 
$$ H_{\et}^n(X_{\overline{K}}, \bQ_{p}) \otimes_{\bQ_{p}} B_{\dR} \cong H_{\dR}^n(X/K) \otimes_{K} B_{\dR}. $$

**Remark.** The filtration on the left-hand side comes from the grading of $B_{\dR}$ (as there is no filtration on étale cohomology). On the right-hand side, we give the convolution filtration.[^convolution filtration]

We are not going to define $B_{\dR}$, but let us list the main properties of $B_{\dR}$. 

**Proposition.** The de Rham period ring $B_{\dR}$ is a filtered $K$-algebra with a continuous $\Gal_{K}$-action such that 

- $\operatorname{gr}(\mathrm{Fil}^{\bullet}(B_{\dR})) = B_{\HT}$, 
- $B_{\dR}^{\Gal_{K}} = K$. 

By the first property, we can recover the Hodge-Tate comparison from de Rham comparison by taking the associated graded vector space. By the second property, we can recover the de Rham cohomology from étale cohomology. 

### 2.3. Crystalline comparison theorem 

The last comparison theorem is the *crystalline comparison*. 

**Theorem (Faltings, crystalline comparison).** Let $K$ be a $p$-adic field with (perfect) residue field $k$ and $K_{0} \coloneqq W(k)[\frac{1}{p}]$ be the maximal unramified subextension. There is a $\Gal_{K}$-stable $K_{0}$-subalgebra $B_{\cris}$ of $B_{\dR}$ such that, for a proper smooth $X$ over $K$ with a good reduction $X_{W(k)}$, we obtain a natural Galois and $\varphi$ equivariant filtration respecting isomorphism 
$$ H_{\et}^{n}(X_{\overline{K}}, \bQ_{p}) \otimes_{\bQ_{p}} B_{\cris} \cong H_{\cris}^{n}(X_{k}/W(k))[\tfrac{1}{p}] \otimes_{K_{0}} B_{\cris} $$
recovering the de Rham comparison after tensoring $B_{\dR}$. 

Again, we are not going to define the period ring $B_{\cris}$. Instead, we list some properties of it. 

**Proposition.** $B_{\cris}$ is a $\Gal_{K}$-stable $K_{0}$-subalgbra of $B_{\dR}$ with the induced filtration. Additionally, it is equipped with a $\varphi$-action whose restruction to $K_{0}$ is the Witt vector Frobenius of $K_{0}$. Also, $B_{\cris}^{\Gal_{K}} = K_{0}$. 

By the last property, we obtain this. 

**Corollary.** $(H_{\et}^{n}(X_{\overline{K}}, \bQ_{p})^{\Gal_{K}} \cong H_{\cris}^{n}(X_{k} / W(k))[\tfrac{1}{p}]$. 

**Remark.** This can be thought of as "crystalline cohomology is the right $p$-adic replacement of étale cohomology". Compare this with the proper-smooth base change theorem for étale cohomology. 

**Theorem (proper-smooth base change, [Milne, Theorem 20.4]).** Let $R$ be a Henselian local domain with fraction field $K$ and residue field $k$. For any $X$ proper smooth scheme over $R$, there is a natural map called a (co)specialization 
$$ \sp: H_{\et}^{n}(X_{k}, \bQ_{\ell}) \to H_{\et}^{n}(X_{K}, \bQ_{\ell}) $$
which is a Galois equivariant isomorphism. 

**Exercise.** Prove the (co)specialization map is Galois equivariant with respect to the reduction map $\Gal_{K} \to \Gal_{k}$. In particular, $H_{\et}^{n}(X_{\overline{K}}, \bQ_{\ell})$ is unramified if $X$ has a good reduction. 

## 3. Period rings and functors

In this section, we will make a formal setup to express what we explained in a categorical language. Throught this section, we fix a p-adic field $K$ and let $B \in \{B_{\HT}, B_{\dR}, B_{\cris}\}$. 

**Definition.** We define a functor $D_{B}: \Rep_{\bQ_{p}}(\Gal_{K}) \to \Vect^{\ast}_{B}$ as 
$$ D_{B}(V) \coloneqq (V \otimes_{\bQ_{p}} B)^{\Gamma}. $$ 
Here, $\Vect^{\ast}_{B}$ is the category of $B^{\Gal_{K}}$-vector spaces with additional structure, where the additional structure is given as follows. 

- If $B = B_{\HT}$, the additional structure is the grading. 
- If $B = B_{\dR}$, the additional structure is the filtration. 
- If $B = B_{\cris}$, the additional structure is the filtration with $\varphi$-action. 

**Definition.** We say a representation $V \in \Rep_{\bQ_{p}}(\Gal_{K})$ is *$B$-admissible* if the natural map 
$$ \alpha_{V}: D_{B}(V) \otimes_{B^{\Gal_{K}}} B \to V \otimes_{\bQ_{p}} (B \otimes_{B^{\Gal_{K}}} B) \to V \otimes_{\bQ_{p}} B $$
is an isomorphism. We denote by $\Rep_{\bQ_{p}}^{B}(\Gal_{K})$ the full subcategory of $\Rep_{\bQ_{p}}(\Gal_{K}$ consisting of $B$-admissible representations. 

**Example.** Let $B = B_{HT}$. Then, the map 
$$ \alpha_{V}: D_{\HT}(V) \otimes_{K} B_{\HT} \to V \otimes_{\bQ_{p}} B_{\HT} $$
is an isomorphism if and only if the $\operatorname{gr}^{0}$-part 
$$ \operatorname{gr}^{0}(\alpha_{V}): \bigoplus_{j \in \bZ} (V \otimes_{\bQ_{p}} \bC_{K}(j))^{\Gal_{K}} \otimes \bC_{K}(-j) \to V \otimes_{\bQ_{p}} \bC_{K} $$
is an isomorphism as the $\operatorname{gr}^{j}$-part is the $j$th Tate twist of $\operatorname{gr}^{0}$-part. 

**Fact (Serre-Tate).** The map $\operatorname{gr}^{0}(\alpha_{V})$ is injective. 

**Corollary.** $\dim_{K_{0}}(D_{\cris}(V)) \le \dim_{K}(D_{\dR}(V)) \le \dim_{K}(D_{\HT}(V)) \le \dim_{\bQ_{p}}(V)$. 

**Proof.** The last inequality follows from Serre-Tate. To prove the first inequality, we need one fact. 

**Fact.** The natural map $B_{\cris} \otimes_{K_{0}} K \to B_{\dR}$ is injective. 

Thus, the natural map 
$$ V \otimes_{\bQ_{p}} (B_{\cris} \otimes_{K_{0}} K) \to V \otimes_{\bQ_{p}} B_{\dR} $$
is injective, and the $\Gal_{K}$-invariant 
$$ (V \otimes_{\bQ_{p}} (B_{\cris} \otimes_{K_{0}} K))^{\Gal_{K}} \to (V \otimes_{\bQ_{p}} B_{\dR})^{\Gal_{K}} $$
is injective as well. The source is $D_{\cris}(V) \otimes_{K_{0}} K$ and the target is $D_{\dR}(V)$. Hence, we obtain $\dim_{K_{0}}(D_{\cris}(V)) \le \dim_{K}(D_{\dR}(V))$. 

The middle inequality follows as 
$$ \dim_{K}(D_{\dR}(V)) = \dim_{K}(\operatorname{gr}^{\bullet}(D_{\dR}(V))) \le \dim_{K}((\operatorname{gr}^{\bullet}(V \otimes_{\bQ_{p}} B_{\dR}))^{\Gal_{K}}) = \dim_{K}(D_{\HT}(V)) $$
by the left-exactness of $\Gal_{K}$-invariant. 

**Remark.** In fact, $\alpha_{V}$ and $\operatorname{gr}^{0}(\alpha_{V})$ being an isomorphism only depends on $V \otimes_{\bQ_{p}} \bC_{K}$. Furthermore, 
$$ D_{\HT}: \Rep_{\bC_{K}}(\Gal_{K}) \to \Vect^{\operatorname{Gr}}_{K} $$
is an equivalence of categories with a quasi-inverse $D \mapsto \operatorname{gr}^{0}(D \otimes_{K} B_{\HT})$ ([Brinon-Conrad, Theorem 2.4.11]). 

In fact, there is a more general result. 

**Theorem.** The natural map $\alpha_{V}$ is injective. In particular, the map $\alpha_{V}$ is an isomorphism if and only if $\dim_{B^{\Gal_{K}}}(V) = \dim_{\bQ_{p}}(V)$. 

**Corollary.** $\Rep_{\bQ_{p}}^{B_{\cris}}(\Gal_{K}) \subset \Rep_{\bQ_{p}}^{B_{\dR}}(\Gal_{K}) \subset \Rep_{\bQ_{p}}^{B_{\HT}}(\Gal_{K})$

**Proof.** If $V$ is $B_{\cris}$-admissible, then 
$$ \dim_{\bQ_{p}}(V) = \dim_{K}(D_{\cris}(V)) \le \dim_{K}(D_{\dR}(V)) \le \dim_{\bQ_{p}}(V). $$
Hence, $V$ is $B_{\dR}$-admissible. Similarly, $B_{\dR}$-admissibility implies $B_{\HT}$-admissibility. 

[^1]: There are various different definitions of $\ell$-adic representation, e.g., using $\overline{\bQ_{\ell}}$ in place of $\bQ_{\ell}$ (and assuming some properties). 
[^2]: Note that we need to fix an embedding $\overline{\bQ} \to \overline{\bQ_{p}}$ to do so. 
[^3]: The grading on the right-hand side is functorial as well. 
[^convolution grading]: For two graded vector spaces $V$ and $W$, the convolution grading on $V \otimes W$ is given by $(V \otimes W)^{n} = \bigoplus_{i+j = n} V^{i} \otimes W^{j}$. 
[^convolution filtration]: For two filtered vector spaces $V$ and $W$, the convolution filtration on $V \otimes W$ is given by $\mathrm{Fil}^{n}(V \otimes W) \coloneqq \sum_{i+j = n} V^{i} \otimes W^{j}$. 
